apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
      command:
        - 'sleep'
      args:
        - '999999'
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
